
services:
  chat-node-1:
    build: .
    container_name: link-chat-node-1
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      chat_bridge:
        ipv4_address: 192.168.100.10
    volumes:
      - ./descargas1:/app/descargas
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - NODE_NAME=Nodo-1
      - DISPLAY=${DISPLAY}
    stdin_open: true
    tty: true
    command: /app/start.sh eth0

  chat-node-2:
    build: .
    container_name: link-chat-node-2
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      chat_bridge:
        ipv4_address: 192.168.100.11
    volumes:
      - ./descargas2:/app/descargas
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - NODE_NAME=Nodo-2
      - DISPLAY=${DISPLAY}
    stdin_open: true
    tty: true
    command: /app/start.sh eth0

  chat-node-3:
    build: .
    container_name: link-chat-node-3
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      chat_bridge:
        ipv4_address: 192.168.100.12
    volumes:
      - ./descargas3:/app/descargas
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - NODE_NAME=Nodo-3
      - DISPLAY=${DISPLAY}
    stdin_open: true
    tty: true
    command: /app/start.sh eth0

networks:
  chat_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24